title: "Glady Samuel"
description: "Data science, bioinformatics, and machine learning projects."
author: "Glady Hazitha Samuel"
theme: jekyll-theme-minimal
show_downloads: true
baseurl: "/datascience"  # IMPORTANT: Add this line for correct linking
url: "https://ghsamuel.github.io"  # Your GitHub Pages URL
github:
  is_project_page: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
